import Hero from "@/components/Hero";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Photo Next.js 13 + TypeScript + Tailwind App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
    </>
  );
};

export default Home;
