import Head from "next/head";
import Hero from "@/components/Hero";
import Slider from "@/components/Slider";
import { SliderData } from "@/data/slider";

const Home = () => {
  return (
    <>
      <Head>
        <title>Photo Next.js 13 + TypeScript + Tailwind App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Photo Site Title"
        text="Здесь небольшой текст про то, как хорошо болтаться по миру и фотографировать!.."
        buttonLabel="clickMe"
      />
      <Slider data={SliderData} />
    </>
  );
};

export default Home;
